### ISSUE TITLE
Travis builds fail because of test verbosity

### ISSUE THREAD

**Issue by ralphlange** [epics-base/jca#28]
Lately, all Travis builds always fail because the tests are generating too much output. This is making the CI system a lot less useful.
Is there anything that could be done about that?

**Comment by willrogers** [comment]
95% of the output is coming from `com.cosylab.epics.caj.test.ChannelSearchTest.testSearch()`. It looks like you get 5 lines from each of 100000 channels.

If we managed to quiet this test down I think Travis would be happy.

**Comment by shroffk** [comment]
all the print outs are from log messages logged at debug or fine 

```
context.getLogger().log(Level.FINE, "Repeater registation request sent to " + repeaterAddress + ".");
```

I tried to add quite build to mvn and printed out the mvn conf logging settings
```
before_script:
 - cat /usr/local/maven-3.5.2/conf/logging/simplelogger.properties

script:
  - mvn -q clean verify
```

The default level is info, so it seems like the logging settings are being tampered with someplace else.

**Comment by shroffk** [comment]
Ok, 

So I updated the CAJContext to print out the system properties and something if turning on 
```CAJ_DEBUG=true```

This means the logging level gets set to Level.ALL...thus the insane level of messaging

I am not sure where this is being set, I will looking into this tom.

**Comment by willrogers** [comment]
I found two things:

* `CAJContextDebugTest` uses `CAJ_DEBUG` to set the logging level to `ALL`. However, since there's a global logger, setting the environment variable back doesn't reset the logging level, so it remains at `ALL` for the rest of the tests
* When I fixed this, I found a lot of exceptions thrown by `CAJChannelSearchTest`. It is something to do with the `CAJTransport` object having been closed at the end of the test but `ClearChannelResponse`s still arriving and being processed afterwards. I made a one-line commit that fixes this, but I don't know if it is the 'correct' way to do it

**Comment by shroffk** [comment]
Thanks @willrogers 

1. I think global logger are deprecated and the use of them is discouraged...
```
     * The "global" Logger object is provided as a convenience to developers
     * who are making casual use of the Logging package.  Developers
     * who are making serious use of the logging package (for example
     * in products) should create and use their own Logger objects,
     * with appropriate names, so that logging can be controlled on a
     * suitable per-Logger granularity.
```

I assume caj is not for cause use and thus maybe this should become an Issue.

2. I am not sure about the shutdown procedure of the CAS...maybe @ralphlange @mdavidsaver or @mrkraimer can shed some light on this.

I have accepted the PR since the changes make sense to me and we can undo them if necessary.

**Comment by willrogers** [comment]
The changes in #37 make the logs much shorter so Travis is happy.
