### ISSUE TITLE
Should jca and caj be still maintained as different projects?

### ISSUE THREAD

**Issue by shroffk** [epics-base/jca#7]
While I understand the appeal of packaging the API and the implementation in separate modules. Are there a lot of use cases where jca is being used without caj?

**Comment by kasemir** [comment]
I'm OK with combining it.
The separation is based on history and different implementers.
It actually made sense from the start to include the pure-java implementation with the API.
The JNI implementation, which depends on the OS-specific binary, would have made more sense as a separate, optional module.

**Comment by anjohnson** [comment]
When Eric Boucher wrote the original implementation there was no intention of ever writing a separate pure Java version. The CA client library had one implementation, written and thoroughly tested by Jeff Hill, which all the different language bindings used, including Java through the JNI code. I think there's even a presentation slide somewhere that gives that as one of the advantages of EPICS!

I can never remember which module is which, so I'm fine with you combining the two into a single project.

**Comment by ralphlange** [comment]
+1 for combining them.

I would suggest keeping the higher level (API) name jca, as this may be less likely to break dependencies. (Technically, only jca had a dependency to caj, right?)

**Comment by shroffk** [comment]
Actually it is caj that has a dependency on jca...

**Comment by berryma4** [comment]
😂

On Jun 29, 2017 8:56 AM, "Kunal Shroff" <notifications@github.com> wrote:

Actually it is caj that has a dependency on jca...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/epics-base/jca/issues/7#issuecomment-311957870>, or mute
the thread

**Comment by ralphlange** [comment]
What I wanted to say:
Any application was only using jca classes (the API), correct?
If the new name is jca, the application does not have to change.
If the new name is caj, every application has to change.

That's why I thought that merging into the jca namespace is less likely to break existing applications.

**Comment by slacmshankar** [comment]
+1 for combining them.

**Comment by jlmuir** [comment]
+1 for combining.

I think the project should be named "Channel Access for Java" and can be abbreviated as CAJ.  This assumes it includes a server, which I believe it does (in `gov.aps.jca.cas`), but I've never used it.

As for @ralphlange's comment on the API, yes I think the API should not be broken.  In its simplest form, this would mean continuing to use the `gov.aps.jca` package and class, interface, etc. names.  Ideally, though, I'd like to see all references to JCA go away, move everything under a new package (e.g., `org.epics.caj`) (it would be great if the EPICS community owned the `epics.org` domain, though), and provide backward-compatible adapters so that existing code can use the latest CAJ without modification, but new code can use the new CAJ API.

**Comment by shroffk** [comment]
It seems like the way to merge the projects with the least amount of changes would be to move the caj implementation into the jca.
All package names will be kept the same.

The java requirements will have to be at least java 7. This is to support for-each loops, support for '<>' operator. There might even be a case to move to java 8 to use the new java.time and the streaming api's.

**Comment by shroffk** [comment]
Resolved:
The two projects have been merged
